stages:
  - build
  - test
  - deploy

buildjob:
  stage: build
  script:
    - ./gradlew assemble
    artifacts:
      paths:
        - build/libs/*.jar
      expire_in: 10 min

test:master:
  stage: test
  image: openjdk:11-jdk
  script:
    - ./gradlew check
  only:
    - master
  dependencies:
    - buildjob

test:branches:
  stage: test
  image: openjdk:11-jdk
  script:
    - ./gradlew check
  only:
    - branches
  except:
    - master
  dependencies:
    - buildjob

deploy:
  stage: deploy
  image: alpine:3.7
  script:
    - echo "Pretending to deploy"
  only:
    - master
  dependencies: []

