stages:
  - build
  - test
  - deploy

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
        
cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches
        
        
buildjob:
  stage: build
  image: openjdk:11-jdk
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 10 min

test:master:
  stage: test
  image: openjdk:11-jdk
  script:
    - ./gradlew test
  only:
    - master
  dependencies:
    - buildjob
  artifacts:
    reports:
      junit: build/test-results/test/**/TEST-*.xml


test:branches:
  stage: test
  image: openjdk:11-jdk
  script:
    - ./gradlew test
  only:
    - branches
  except:
    - master
  dependencies:
    - buildjob
  artifacts:
    reports:
      junit: build/test-results/test/**/TEST-*.xml
    paths:
      - build/test-results/test/**/TEST-*.xml
    expire_in: 10 min

deploy:
  stage: deploy
  image: alpine:3.7
  script:
    - echo "Pretending to deploy"
  only:
    - master
  dependencies: []

